<?php

?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \MageWorx\GreenDeliveryBase\ViewModel\OptionJsConfig $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isDisplayed()): ?>
<div id="block-green-delivery-description" style="display: none"
     class="block green-delivery-description-container">
    <span><?= $escaper->escapeHtml($viewModel->getDescription()) ?></span>
</div>
    <script>
        require(['jquery'], function ($) {
            $('#shipping-method-form').append($('#block-green-delivery-description'));

            changeGreenDeliveryDescriptionVisibility($('#shipping-method').find(":selected").val());

            $("#shipping-method").change(function() {
                changeGreenDeliveryDescriptionVisibility($(this).val());
            });

            function changeGreenDeliveryDescriptionVisibility(method) {
                if (method.trim() != '' && method.search('mageworxgreendelivery_') === 0) {
                    $('#block-green-delivery-description').show();
                } else {
                    $('#block-green-delivery-description').hide();
                }
            }
        });
    </script>
<?php endif; ?>
